Name = "DrExample" #The name he uses to connect
no_absolute_paths = True
debug_on = False
SName = ["cc","nt","trasen","nano","nanotrasen"] #Other names he will respond to, in lowercase
DISABLE_ALL_NON_MANDATORY_SOCKET_CONNECTIONS = False
directory = "C:\Users\Ample\Documents\aeiou\VOREStation-testing\VOREStation\bot/" # Directory the bot is located in, make sure to keep the "/" at the end
version = "TG CC-BY-SA 6"
Network = 'chat.freenode.net' #e.g. "irc.rizon.net"
channel = "#SS13Devs" #what channel you want the bot in
channels = ["#SS13Devs"] #same as above
greeting = "Welcome!" #what he says when a person he hasn't seen before joins
prefix = "!" #prefix for bot commands
Port = 7000
